apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: sqlserver-debezium-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.hostname: "server.earth.svc"
    database.port: "1433"
    database.user: "sa"
    database.password: "Abcd1234"
    database.names: "InternationalDB"
    database.encrypt: false
    topic.prefix: "server.earth"
    table.include.list: "dbo.Orders"
    schema.history.internal.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    schema.history.internal.kafka.topic: "server.earth.schema-changes"
